export const TRADINGPAGE_VERTICAL_COMBO_CHANGE = 'TRADINGPAGE_VERTICAL_COMBO_CHANGE';
export type TRADINGPAGE_VERTICAL_COMBO_CHANGE = typeof TRADINGPAGE_VERTICAL_COMBO_CHANGE;


export const TRADINGPAGE_HORIZONTAL_COMBO_CHANGE = 'TRADINGPAGE_HORIZONTAL_COMBO_CHANGE';
export type TRADINGPAGE_HORIZONTAL_COMBO_CHANGE = typeof TRADINGPAGE_HORIZONTAL_COMBO_CHANGE;

export const TRADINGPAGE_CREATE_BUTTON_CLICK = 'TRADINGPAGE_CREATE_BUTTON_CLICK';
export type TRADINGPAGE_CREATE_BUTTON_CLICK = typeof TRADINGPAGE_CREATE_BUTTON_CLICK;

